//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrameworkTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class New {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal New() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrameworkTask.Properties.New", typeof(New).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 129.
        /// </summary>
        internal static string commitUsage {
            get {
                return ResourceManager.GetString("commitUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to europe-west3.
        /// </summary>
        internal static string datacenter {
            get {
                return ResourceManager.GetString("datacenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVIDIA_TESLA_T4.
        /// </summary>
        internal static string gpuType {
            get {
                return ResourceManager.GetString("gpuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string localSSD {
            get {
                return ResourceManager.GetString("localSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP-COMPUTEENGINE-VMIMAGE-N1-HIGHMEM-16.
        /// </summary>
        internal static string machineType {
            get {
                return ResourceManager.GetString("machineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string numberOfGPU {
            get {
                return ResourceManager.GetString("numberOfGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string numberOfInstances {
            get {
                return ResourceManager.GetString("numberOfInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to win.
        /// </summary>
        internal static string os {
            get {
                return ResourceManager.GetString("os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regular.
        /// </summary>
        internal static string provisionModel {
            get {
                return ResourceManager.GetString("provisionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n1.
        /// </summary>
        internal static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
    }
}
